name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        go-version: [ 1.17, 1.18, 1.19, '1.20' ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Enforce standard format
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.2
          args: --timeout 3m --enable=gofmt --verbose
      - name: Test
        run: go test --cover -v ./...
      - name: Build
        run: go build -v ./...
