name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GOLANGCI_LINT_VERSION: "v1.58.0"

jobs:
  build:
    strategy:
      matrix:
        go-version: [ '1.17', '1.18', '1.19', '1.20', '1.21']
        os: [ ubuntu-22.04, macos-12, windows-2022 ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Enforce standard format
        uses: golangci/golangci-lint-action@3cfe3a4abbb849e10058ce4af15d205b6da42804 # v3.7.1
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          args: --timeout 3m --enable=gofmt --verbose
      - name: Test
        run: go test --cover -v ./...
      - name: Build
        run: go build -v ./...
